### ISSUE TITLE
Error faced "Error while calling ssm:SendCommand: InvalidInstanceId" while triggering pipeline

### ISSUE THREAD

**Issue by Ramneek-kalra** [aws-samples/pipeline-for-hardening-eks-nodes-and-automating-updates#2]
Good Day @nimaft , 

I am helping one of the Enterprise Customer where they're facing issues for triggering this solution and logs for the same are attached with this issue.

You can see the parameters being used for their CFN Stack as below:

![image](https://github.com/user-attachments/assets/02b95a8b-6a73-4f1f-ab73-fd89fbfa08ad)

Meanwhile, I am also test-replicating to understand the gaps here. We are following - https://aws.amazon.com/blogs/security/how-to-create-a-pipeline-for-hardening-amazon-eks-nodes-and-automate-updates/

- Error CloudWatch Logs: [log-events-viewer-result.csv](https://github.com/user-attachments/files/16230049/log-events-viewer-result.csv)

**Comment by Ramneek-kalra** [comment]
When I test-replicate, I could bypass above error, however getting below issue, unsure of why?
```
CmdExecution: Stderr: [WARNING]: provided hosts list is empty, only localhost is available. Note that
the implicit localhost does not match 'all'
ERROR! 'notify' is not a valid attribute for a Block

The error appears to be in '/ansible/roles/AMAZON-CIS/tasks/prelim.yml': line 213, column 3, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:


- name: "PRELIM | Optional | If IPv6 disable to stop chronyd listening"
  ^ here
```

**Comment by Ramneek-kalra** [comment]
As researched further, I see it's originating from - https://github.com/ansible-lockdown/AMAZON2-CIS/blob/devel/tasks/prelim.yml 

And as figured out, this isn't supported with some version of Ansible. Unsure of what has been used by this CFN Solution.

**Comment by nimaft** [comment]
Hi @Ramneek-kalra, 
The issue you're mentioning is not related to Ansible, your pipeline does not even get to the point of running Ansible. There seems to be an issue with SSM. Make sure:

1. You have the AWSServiceRoleForImageBuilder service-linked role enabled in your account
2. This [line](https://github.com/aws-samples/pipeline-for-hardening-eks-nodes-and-automating-updates/blob/d18d0b33d3e5775c4f1e7588ab78ff4a8d94b895/CloudFormation/AMI-Pipeline-Auto-Replace.yml#L173) is not modified
3. SSM service can communicate with instances in your environment

**Comment by nimaft** [comment]
@Ramneek-kalra turned out the issue was caused due to some incompatibility between Ansible 2.9 installed by AL2 Linux extras and newest updates of Ansible Lockdown AL2 CIS benchmark role. Ansible 2.9 does not support `notify` property for a `block`, so I changed the code to install Ansible using `pip`. This should fix the problem.

**Comment by Ramneek-kalra** [comment]
Thanks @nimaft for your investigation and support here. I am testing it on my test-account, let me revert back if I face any further issue.

**Comment by Ramneek-kalra** [comment]
@nimaft , Good News, we got 70-80% work done, however in the step function of NodeGroup Update, we got failed with below error:

![image](https://github.com/user-attachments/assets/aa366979-bf08-404a-a3e7-fba44157a6d8)

- Logs are here: [log-events-viewer-result.csv](https://github.com/user-attachments/files/16260352/log-events-viewer-result.csv)
- Execution Inputs which were passed: [c832bc84-db59-470c-836b-b4b01712fb03.json](https://github.com/user-attachments/files/16260397/c832bc84-db59-470c-836b-b4b01712fb03.json)

**Comment by Ramneek-kalra** [comment]
Hey @nimaft , Good News!! I did just check that I was lagging the commit and was using the Main-Branch when I git-clone and the same might be in the case of Customer.

Solution is working smoothly when I have a nodegroup with customer-template already there in EKS Cluster and it updates as well as expected.

Thank you so much for your AWSome work here!! 🔥 💯 🥇 

Please close the issue once we have merged 2nd Branch with 1st one now.

**Comment by Ramneek-kalra** [comment]
Thanks for merging the branches! Closing the issue now. I will update back to customer and get this working.
